export enum MongoDBOps {
  find = 'find',
  findOne = 'findOne',
  count = 'count',
  countDocuments = 'countDocuments',
  findOneAndUpdate = 'findOneAndUpdate',
  findOneAndDelete = 'findOneAndDelete',
  findOneAndRemove = 'findOneAndRemove',
  findOneAndReplace = 'findOneAndReplace',
  remove = 'remove',
  update = 'update',
  deleteOne = 'deleteOne',
  deleteMany = 'deleteMany',
  save = 'save',
  aggregate = 'aggregate',
}
